server:
  port: 8080

# 日志相关配置
logging:
  config: classpath:logback-spring.xml

openid:
  list: 自定义openid1,自定义openid2


# 微信相关配置
wechat:
  # 微信公众号appid
  appID: 公众号的appID
  # 微信公众号appSecret
  appsecret: 公众号的appSecret
  # 获取 access_token 地址
  getAccessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  # 模版推送地址
  tmplmsgUrl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=%s
  #